[package]
name = "flow-synth"
version = "0.1.0"
authors = ["Noah Weninger <nweninge@ualberta.ca>"]

[dependencies]
modular-flow = { path = "../modular-flow" }
glutin = "*"
gfx = "*"
gfx_window_glutin = "*"
gfx_text = { git = "https://github.com/PistonDevelopers/gfx_text" }
gfx_device_gl = "*"
