[package]
name = "flow-synth"
version = "0.1.0"
authors = ["Noah Weninger <nweninge@ualberta.ca>"]

[dependencies]
glutin = "0.13.1"
gfx = "*"
gfx_window_glutin = "0.21.0"
gfx_text = "*"
gfx_device_gl = "*"
num = "*"
futures = "*"
crossbeam = "*"
jack = "*"
ndarray = "*"
nfd = "*"
notify = "4.x"
